<?php $flash=get_flash(); ?>
<div class="ao-hero-slim"><div class="cp-page-head"><div><h2>Güvenlik Merkezi</h2><p>Admin ve müşteri girişleri için Mail OTP, Google Authenticator ve SMS OTP seçeneklerini yönetin.</p></div><a class="ao-btn" href="<?= url('admin/settings/security') ?>">Detaylı Ayarlar</a></div></div>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-card"><h3>Giriş Doğrulama Politikaları</h3><form method="post" action="<?= url('admin/security/settings-save') ?>" class="ao-form"><?= csrf_field() ?><div class="ao-form-grid">
<label>Admin 2FA Politikası<select name="admin_mfa_policy"><option value="off" <?= admin_setting('admin_mfa_policy','optional')==='off'?'selected':'' ?>>Kapalı</option><option value="optional" <?= admin_setting('admin_mfa_policy','optional')==='optional'?'selected':'' ?>>İsteğe Bağlı</option><option value="required" <?= admin_setting('admin_mfa_policy','optional')==='required'?'selected':'' ?>>Zorunlu</option></select></label>
<label>Müşteri 2FA Politikası<select name="customer_mfa_policy"><option value="off" <?= admin_setting('customer_mfa_policy','optional')==='off'?'selected':'' ?>>Kapalı</option><option value="optional" <?= admin_setting('customer_mfa_policy','optional')==='optional'?'selected':'' ?>>İsteğe Bağlı</option><option value="required" <?= admin_setting('customer_mfa_policy','optional')==='required'?'selected':'' ?>>Zorunlu</option></select></label>
<label>Varsayılan Yöntem<select name="mfa_default_method"><option value="mail" <?= admin_setting('mfa_default_method','mail')==='mail'?'selected':'' ?>>Mail OTP</option><option value="totp" <?= admin_setting('mfa_default_method','mail')==='totp'?'selected':'' ?>>Google Authenticator</option><option value="sms" <?= admin_setting('mfa_default_method','mail')==='sms'?'selected':'' ?>>SMS OTP</option></select></label>
<label><input type="checkbox" name="mfa_mail_enabled" value="1" <?= admin_setting('mfa_mail_enabled','1')==='1'?'checked':'' ?>> Mail OTP aktif</label>
<label><input type="checkbox" name="mfa_totp_enabled" value="1" <?= admin_setting('mfa_totp_enabled','1')==='1'?'checked':'' ?>> Google Authenticator aktif</label>
<label><input type="checkbox" name="mfa_sms_enabled" value="1" <?= admin_setting('mfa_sms_enabled','0')==='1'?'checked':'' ?>> SMS OTP aktif</label>
<label>OTP Süresi (dakika)<input name="mfa_otp_ttl_minutes" value="<?= e(admin_setting('mfa_otp_ttl_minutes','5')) ?>"></label>
<label>Maksimum Deneme<input name="mfa_max_attempts" value="<?= e(admin_setting('mfa_max_attempts','5')) ?>"></label>
<label>SMS Gönderici<input name="mfa_sms_sender" value="<?= e(admin_setting('mfa_sms_sender','AhostOne')) ?>"></label>
<label>IP Whitelist<textarea name="ip_whitelist" rows="3" placeholder="Her satıra bir IP"><?= e(admin_setting('ip_whitelist','')) ?></textarea></label>
<label>Oturum Süresi (dakika)<input name="session_timeout_minutes" value="<?= e(admin_setting('session_timeout_minutes','60')) ?>"></label>
<label><input type="checkbox" name="csrf_protection" value="1" <?= admin_setting('csrf_protection','1')==='1'?'checked':'' ?>> CSRF koruması</label>
<label><input type="checkbox" name="rate_limit_login" value="1" <?= admin_setting('rate_limit_login','1')==='1'?'checked':'' ?>> Login rate limit</label>
</div><button class="ao-btn">Kaydet</button></form></div>
<div class="ao-card"><h3>Son Giriş / 2FA Logları</h3><div class="ao-table-wrap"><table class="ao-table"><thead><tr><th>Tarih</th><th>Tip</th><th>E-posta</th><th>Olay</th><th>Yöntem</th><th>Durum</th><th>IP</th></tr></thead><tbody><?php ao_mfa_ensure_schema(); try{$rows=db()->query('SELECT * FROM auth_login_events ORDER BY id DESC LIMIT 20')->fetchAll();}catch(Throwable $e){$rows=[];} foreach($rows as $r): ?><tr><td><?= e($r['created_at']) ?></td><td><?= e($r['user_type']) ?></td><td><?= e($r['email']) ?></td><td><?= e($r['event_type']) ?></td><td><?= e($r['method']) ?></td><td><?= e($r['status']) ?></td><td><?= e($r['ip_address']) ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="7" class="muted">Henüz güvenlik logu yok.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="ao-card"><h3>Yetki Kapsamları</h3><div class="ao-badges"><span>customers.view</span><span>orders.manage</span><span>billing.manage</span><span>domains.manage</span><span>hosting.manage</span><span>marketplace.manage</span><span>settings.manage</span><span>security.manage</span></div></div>
