<?php $rows=[]; $regs=[]; $logs=[]; $flash=get_flash(); try{ if(function_exists('ao_v2410_ensure_schema')) ao_v2410_ensure_schema(); $rows=db()->query('SELECT * FROM tld_pricing ORDER BY tld')->fetchAll();$regs=db()->query('SELECT slug,name FROM domain_registrars ORDER BY name')->fetchAll(); try{$logs=db()->query('SELECT * FROM domain_price_import_logs ORDER BY id DESC LIMIT 8')->fetchAll() ?: [];}catch(Throwable $e){} }catch(Throwable $e){} ?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-page-head"><div><span class="ao-kicker">Domain Center</span><h2>TLD Fiyatları</h2><p>Kayıt, transfer, yenileme, restore ve maliyet/marj yönetimi.</p></div><a class="ao-btn soft" href="<?= url('admin/domain-center/registrars') ?>">Registrarlar</a></div>
<div class="ao-grid two">
<div class="ao-card"><h3>Manuel Fiyat</h3><form class="ao-form" method="post" action="<?= url('admin/domain-center/pricing-save') ?>"><?= csrf_field() ?><div class="ao-form-grid"><label>TLD<input name="tld" placeholder=".com"></label><label>Kayıt<input name="register_price" type="number" step="0.01" value="499.00"></label><label>Transfer<input name="transfer_price" type="number" step="0.01" value="449.00"></label><label>Yenileme<input name="renew_price" type="number" step="0.01" value="499.00"></label><label>Para Birimi<input name="currency" value="TRY"></label><label>Registrar<select name="registrar_slug"><?php foreach($regs as $r): ?><option value="<?= e($r['slug']) ?>"><?= e($r['name']) ?></option><?php endforeach; ?></select></label></div><button class="ao-btn">Fiyat Kaydet / Güncelle</button></form></div>
<div class="ao-card"><h3>Registrar Fiyat Aktarımı</h3><p class="ao-muted">Registrar bağlantı testleri ve canlı sorgularla doğrulanmış fiyat önbelleğini satış marjıyla TLD fiyatlarına aktarır. Şablon maliyet kullanılmaz.</p><form class="ao-form" method="post" action="<?= url('admin/domain-center/pricing-import') ?>"><?= csrf_field() ?><div class="ao-form-grid"><label>Registrar<select name="registrar_slug"><?php foreach($regs as $r): ?><option value="<?= e($r['slug']) ?>"><?= e($r['name']) ?></option><?php endforeach; ?><option value="domainnameapi">DomainNameAPI</option><option value="resellerclub">ResellerClub</option></select></label><label>Satış Marjı %<input name="margin_percent" type="number" step="0.01" value="25"></label></div><button class="ao-btn">Doğrulanmış Fiyatları Aktar</button></form><?php if($logs): ?><div class="ao-mini-log"><?php foreach($logs as $l): ?><div><strong><?= e($l['registrar_slug']) ?></strong> <?= (int)$l['imported_count'] ?> kayıt <small><?= e($l['created_at']) ?></small></div><?php endforeach; ?></div><?php endif; ?></div>
</div>
<div class="ao-card"><table class="ao-table"><thead><tr><th>TLD</th><th>Maliyet</th><th>Kayıt</th><th>Transfer</th><th>Yenileme</th><th>Restore</th><th>Marj</th><th>Registrar</th><th>Durum</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= e($r['tld']) ?></strong></td><td><?= number_format((float)($r['cost_price']??0),2,',','.') ?></td><td><?= number_format((float)$r['register_price'],2,',','.') ?> <?= e($r['currency']) ?></td><td><?= number_format((float)$r['transfer_price'],2,',','.') ?> <?= e($r['currency']) ?></td><td><?= number_format((float)$r['renew_price'],2,',','.') ?> <?= e($r['currency']) ?></td><td><?= number_format((float)($r['restore_price']??0),2,',','.') ?> <?= e($r['currency']) ?></td><td>%<?= number_format((float)($r['margin_percent']??0),2,',','.') ?></td><td><?= e($r['registrar_slug']) ?></td><td><?= $r['is_active']?'Aktif':'Pasif' ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="9">Fiyat kaydı yok.</td></tr><?php endif; ?></tbody></table></div>
<?php /* RC12: inline style removed; visual layer is centralized. */ ?>
