<?php
$id=(int)($_GET['id']??0); $flash=get_flash(); $d=$c=null; $dns=[]; $ns=[]; $contact=[];
try{
 $q=db()->prepare('SELECT d.*,c.first_name,c.last_name,c.email FROM domains d LEFT JOIN customers c ON c.id=d.customer_id WHERE d.id=?'); $q->execute([$id]); $d=$q->fetch();
 if($d){ $dnsq=db()->prepare('SELECT * FROM domain_dns_records WHERE domain_id=? ORDER BY record_type,host'); $dnsq->execute([$id]); $dns=$dnsq->fetchAll(); $nsq=db()->prepare('SELECT * FROM domain_nameservers WHERE domain_id=?'); $nsq->execute([$id]); $ns=$nsq->fetch() ?: []; $cq=db()->prepare('SELECT * FROM domain_contacts WHERE domain_id=? LIMIT 1'); $cq->execute([$id]); $contact=$cq->fetch() ?: []; }
}catch(Throwable $e){}
?>
<?php if(!$d): ?><div class="ao-card"><h2>Domain bulunamadı</h2><a class="ao-btn" href="<?= url('admin/domain-center') ?>">Listeye Dön</a></div><?php return; endif; ?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-page-head" data-domain-widget><div><h2><?= e($d['domain_name']) ?></h2><p><?= e(($d['first_name']??'').' '.($d['last_name']??'')) ?> · Registrar: <?= e($d['registrar'] ?? ($d['registrar_name'] ?? (!empty($d['registrar_id']) ? ('Registrar #'.(int)$d['registrar_id']) : 'DomainNameAPI'))) ?> · Durum: <?= e($d['status']) ?></p></div><div><input type="hidden" data-domain-input value="<?= e($d['domain_name']) ?>"><button class="ao-mini-btn" data-domain-tool="whois">WHOIS Popup</button> <button class="ao-mini-btn" data-domain-tool="dns">DNS Popup</button> <button class="ao-mini-btn" data-domain-tool="ssl">SSL Popup</button> <button class="ao-mini-btn" data-domain-tool="valuation">Değerleme</button> <a class="ao-btn soft" href="<?= url('admin/domain-center') ?>">Listeye Dön</a></div></div>
<div class="ao-card ao-tab-shell" data-ao-tabs>
 <div class="ao-real-tabs"><button class="active" data-tab="genel">Genel</button><button data-tab="dns">DNS Zone</button><button data-tab="nameserver">Nameserver</button><button data-tab="whois">WHOIS</button><button data-tab="epp">EPP / Lock</button><button data-tab="islem">İşlemler</button></div>
 <section id="tab-genel" class="ao-tab-panel active"><h3>Domain Bilgileri</h3><div class="ao-info-list"><p><strong>Domain:</strong> <?= e($d['domain_name']) ?></p><p><strong>Kayıt:</strong> <?= e($d['registration_date']) ?></p><p><strong>Bitiş:</strong> <?= e($d['expiry_date']) ?></p><p><strong>Oto Yenileme:</strong> <?= $d['auto_renew']?'Açık':'Kapalı' ?></p><p><strong>Kilit:</strong> <?= $d['lock_status']?'Kilitli':'Açık' ?></p></div></section>
 <section id="tab-dns" class="ao-tab-panel"><h3>DNS Zone Yönetimi</h3><table class="ao-table"><tr><th>Tip</th><th>Host</th><th>Değer</th><th>Öncelik</th><th>TTL</th><th></th></tr><?php foreach($dns as $r): ?><tr><td><?= e($r['record_type']) ?></td><td><?= e($r['host']) ?></td><td><?= e($r['record_value']) ?></td><td><?= e($r['priority']) ?></td><td><?= e($r['ttl']) ?></td><td><a class="ao-mini-btn" href="<?= url('admin/domain-center/dns-delete?id='.(int)$r['id'].'&domain_id='.(int)$d['id'].'&customer_id='.(int)$d['customer_id']) ?>">Sil</a></td></tr><?php endforeach; if(!$dns): ?><tr><td colspan="6">DNS kaydı yok.</td></tr><?php endif; ?></table><form class="ao-form" method="post" action="<?= url('admin/domain-center/dns-save') ?>"><input type="hidden" name="domain_id" value="<?= (int)$d['id'] ?>"><input type="hidden" name="customer_id" value="<?= (int)$d['customer_id'] ?>"><div class="ao-form-grid"><label>Tip<select name="record_type"><option>A</option><option>AAAA</option><option>CNAME</option><option>MX</option><option>TXT</option><option>SRV</option><option>CAA</option></select></label><label>Host<input name="host" value="@"></label><label>Değer<input name="record_value"></label><label>Öncelik<input name="priority" type="number"></label><label>TTL<input name="ttl" type="number" value="3600"></label></div><button class="ao-btn">DNS Kaydı Ekle</button></form></section>
 <section id="tab-nameserver" class="ao-tab-panel"><h3>Nameserver Yönetimi</h3><form class="ao-form" method="post" action="<?= url('admin/domain-center/ns-save') ?>"><input type="hidden" name="domain_id" value="<?= (int)$d['id'] ?>"><input type="hidden" name="customer_id" value="<?= (int)$d['customer_id'] ?>"><div class="ao-form-grid"><label>NS1<input name="ns1" value="<?= e($ns['ns1']??'') ?>"></label><label>NS2<input name="ns2" value="<?= e($ns['ns2']??'') ?>"></label><label>NS3<input name="ns3" value="<?= e($ns['ns3']??'') ?>"></label><label>NS4<input name="ns4" value="<?= e($ns['ns4']??'') ?>"></label></div><button class="ao-btn">Nameserver Güncelle</button></form></section>
 <section id="tab-whois" class="ao-tab-panel"><h3>WHOIS / İletişim</h3><div class="ao-info-list"><p><strong>Ad Soyad:</strong> <?= e($contact['full_name']??'-') ?></p><p><strong>Firma:</strong> <?= e($contact['company']??'-') ?></p><p><strong>E-posta:</strong> <?= e($contact['email']??($d['email']??'-')) ?></p><p><strong>Telefon:</strong> <?= e($contact['phone']??'-') ?></p><p><strong>Adres:</strong> <?= e(($contact['city']??'').' '.($contact['country']??'')) ?></p></div></section>
 <section id="tab-epp" class="ao-tab-panel"><h3>EPP / Kilit / Oto Yenileme</h3><div class="ao-info-list"><p><strong>EPP:</strong> <code><?= e(($d['epp_code'] ?? ($d['auth_code'] ?? '')) ?: 'Henüz yok') ?></code></p><p><strong>Kilit:</strong> <?= $d['lock_status']?'Kilitli':'Açık' ?></p><p><strong>Oto Yenileme:</strong> <?= $d['auto_renew']?'Açık':'Kapalı' ?></p></div></section>
 <section id="tab-islem" class="ao-tab-panel"><h3>Registrar İşlemleri</h3><div class="domain-action-stack"><?php foreach(['renew'=>'1 Yıl Yenile','transfer'=>'Transfer Bekliyor Yap','toggle-lock'=>'Kilit Aç/Kapat','toggle-autorenew'=>'Oto Yenileme Aç/Kapat'] as $act=>$label): ?><form method="post" action="<?= url('admin/customers/domain-action') ?>"><input type="hidden" name="customer_id" value="<?= (int)$d['customer_id'] ?>"><input type="hidden" name="domain_id" value="<?= (int)$d['id'] ?>"><input type="hidden" name="domain_action" value="<?= e($act) ?>"><button class="ao-light-btn"><?= e($label) ?></button></form><?php endforeach; ?></div></section>
</div>
