<?php
$flash=get_flash(); $groups=[]; $customers=[];
try{ ao_schema_ensure_v790(); $groups=db()->query('SELECT g.*, (SELECT COUNT(*) FROM customers c WHERE c.group_id=g.id) customer_count FROM customer_groups g ORDER BY id DESC')->fetchAll(); $customers=db()->query('SELECT id,first_name,last_name,email,group_id FROM customers WHERE status<>"deleted" ORDER BY first_name,last_name')->fetchAll(); }catch(Throwable $e){}
?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-page-head"><div><h2>Müşteri Grupları</h2><p>Segment, indirim, toplu mail/SMS ve müşteri atama merkezi.</p></div></div>
<div class="ao-grid two"><div class="ao-card"><h3>Yeni Grup</h3><form method="post" action="<?= url('admin/customers/group-save') ?>" class="ao-form"><?= csrf_field() ?><label>Grup Adı<input name="name" required placeholder="VIP Müşteriler"></label><label>İndirim %<input type="number" step="0.01" name="discount_percent" value="0"></label><label>Açıklama<textarea name="description" rows="3"></textarea></label><button class="ao-btn">Kaydet</button></form></div><div class="ao-card"><h3>Müşteriyi Gruba Ata</h3><form method="post" action="<?= url('admin/customers/group-assign') ?>" class="ao-form"><?= csrf_field() ?><label>Müşteri<select name="customer_id"><?php foreach($customers as $c): ?><option value="<?= (int)$c['id'] ?>"><?= e($c['first_name'].' '.$c['last_name'].' - '.$c['email']) ?></option><?php endforeach; ?></select></label><label>Grup<select name="group_id"><?php foreach($groups as $g): ?><option value="<?= (int)$g['id'] ?>"><?= e($g['name']) ?></option><?php endforeach; ?></select></label><button class="ao-btn">Ata</button></form></div></div>
<div class="ao-card"><h3>Gruplar</h3><table class="ao-table"><thead><tr><th>Grup</th><th>İndirim</th><th>Müşteri</th><th>Durum</th></tr></thead><tbody><?php foreach($groups as $g): ?><tr><td><strong><?= e($g['name']) ?></strong><br><small><?= e($g['description']) ?></small></td><td>%<?= number_format((float)$g['discount_percent'],2,',','.') ?></td><td><?= (int)$g['customer_count'] ?></td><td><?= !empty($g['is_active'])?'Aktif':'Pasif' ?></td></tr><?php endforeach; if(!$groups): ?><tr><td colspan="4">Henüz grup yok.</td></tr><?php endif; ?></tbody></table></div>
<div class="ao-card"><h3>Toplu Mail / SMS Kuyruğu</h3><form method="post" action="<?= url('admin/customers/bulk-message') ?>" class="ao-form"><?= csrf_field() ?><div class="ao-form-grid"><label>Grup<select name="group_id"><option value="0">Tüm müşteriler</option><?php foreach($groups as $g): ?><option value="<?= (int)$g['id'] ?>"><?= e($g['name']) ?></option><?php endforeach; ?></select></label><label>Kanal<select name="channel"><option value="email">E-posta</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><label class="full">Konu<input name="subject" value="Ahost One Bilgilendirme"></label><label class="full">Mesaj<textarea name="message" rows="4" required></textarea></label></div><button class="ao-btn">Kuyruğa Al</button></form></div>
