<?php
$flash=get_flash();
$customers=[];
try { ao_schema_ensure_v780(); $show=$_GET['show']??'active'; $where=$show==='deleted' ? 'c.status="deleted"' : 'c.status<>"deleted"'; $customers=db()->query('SELECT c.*, (SELECT COUNT(*) FROM services s WHERE s.customer_id=c.id) services_count, (SELECT MIN(s.next_due_date) FROM services s WHERE s.customer_id=c.id AND s.status IN ("active","suspended")) next_service_due, (SELECT COUNT(*) FROM domains d WHERE d.customer_id=c.id) domains_count, (SELECT MIN(d.expiry_date) FROM domains d WHERE d.customer_id=c.id AND d.status="active") next_domain_due, (SELECT COUNT(*) FROM invoices i WHERE i.customer_id=c.id AND i.status="unpaid") unpaid_count FROM customers c WHERE '.$where.' ORDER BY c.id DESC LIMIT 200')->fetchAll(); } catch(Throwable $e) {}
?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-page-head"><div><h2>Müşteriler Modülü Pro</h2><p>Ahost One mantığında müşteri listesi, profil kartı, hizmet/domain/fatura/destek ilişkileri ve hızlı işlemler.</p></div><div class="ao-actions no-margin"><a class="ao-light-btn" href="<?= url('admin/customers') ?>">Aktif/Pasif</a><a class="ao-light-btn" href="<?= url('admin/customers?show=deleted') ?>">Silinenler</a><a class="ao-btn" href="<?= url('admin/customers/add') ?>">+ Yeni Müşteri</a></div></div>
<div class="ao-stats-grid"><div class="ao-stat"><span>Toplam Müşteri</span><strong><?= table_count('customers') ?></strong></div><div class="ao-stat"><span>Aktif Hizmet</span><strong><?= table_count('services') ?></strong></div><div class="ao-stat"><span>Domain</span><strong><?= table_count('domains') ?></strong></div><div class="ao-stat"><span>Açık Ticket</span><strong><?= table_count('tickets') ?></strong></div></div>
<div class="ao-card"><h3>Müşteri Listesi</h3><div class="admin-customer-search"><input type="search" id="adminCustomerQuickSearch" placeholder="Ad, e-posta, telefon, firma, müşteri ID veya durum ara..."><span class="hint">Anlık filtreleme</span></div><table class="ao-table"><thead><tr><th>ID</th><th>Müşteri</th><th>E-posta</th><th>Durum</th><th>Hizmet</th><th>Hosting Yenileme</th><th>Domain</th><th>Domain Yenileme</th><th>Bakiye</th><th>İşlem</th></tr></thead><tbody><?php foreach($customers as $c): ?><tr><td>#<?= (int)$c['id'] ?></td><td><a class="customer-name-link" href="<?= url('admin/customers/view?id='.(int)$c['id']) ?>"><?= e($c['first_name'].' '.$c['last_name']) ?></a><br><small><?= e($c['company_name'] ?: 'Bireysel') ?></small></td><td><?= e($c['email']) ?></td><td><span class="ao-badge <?= e($c['status']) ?>"><?= e($c['status']) ?></span></td><td><?= (int)$c['services_count'] ?></td><td><?= e($c['next_service_due'] ?: '-') ?></td><td><?= (int)$c['domains_count'] ?></td><td><?= e($c['next_domain_due'] ?: '-') ?></td><td><?= number_format((float)$c['balance'],2,',','.') ?> ₺</td><td><?php if(($c['status']??'')==='deleted'): ?><a class="ao-mini-btn" href="<?= url('admin/customers/restore?id='.(int)$c['id'].'&csrf_token='.csrf_token()) ?>">Geri Yükle</a> <a class="ao-mini-btn danger" onclick="return confirm('Bu müşteri ve bağlı kayıtlar kalıcı silinsin mi?')" href="<?= url('admin/customers/permanent-delete?id='.(int)$c['id'].'&csrf_token='.csrf_token()) ?>">Kalıcı Sil</a><?php else: ?><a class="ao-mini-btn" href="<?= url('admin/customers/view?id='.(int)$c['id']) ?>">Profili Aç</a> <a class="ao-mini-btn" href="<?= url('admin/customers/view?id='.(int)$c['id'].'#tab-genel') ?>">Düzenle</a> <a class="ao-mini-btn danger" onclick="return confirm('Müşteri kapalı duruma alınsın mı?')" href="<?= url('admin/customers/close?id='.(int)$c['id'].'&csrf_token='.csrf_token()) ?>">Kapat</a> <a class="ao-mini-btn danger" onclick="return confirm('Müşteri çöp kutusuna taşınsın mı?')" href="<?= url('admin/customers/delete?id='.(int)$c['id'].'&csrf_token='.csrf_token()) ?>">Sil</a><?php endif; ?></td></tr><?php endforeach; if(!$customers): ?><tr><td colspan="10">Henüz müşteri yok.</td></tr><?php endif; ?></tbody></table></div>

<script>
document.addEventListener('DOMContentLoaded',function(){
  var input=document.getElementById('adminCustomerQuickSearch'); if(!input) return;
  var rows=[].slice.call(document.querySelectorAll('.ao-card table.ao-table tbody tr'));
  input.addEventListener('input',function(){
    var q=this.value.toLocaleLowerCase('tr-TR').trim();
    rows.forEach(function(row){ row.style.display = !q || row.textContent.toLocaleLowerCase('tr-TR').indexOf(q)>-1 ? '' : 'none'; });
  });
});
</script>
