<?php
$flash=get_flash(); $rows=[]; $servers=[];
try{
 $rows=db()->query('SELECT h.*, s.status service_status, s.domain, s.customer_id, c.first_name, c.last_name, c.email, p.name product_name FROM hosting_accounts h LEFT JOIN services s ON s.id=h.service_id LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN products p ON p.id=s.product_id ORDER BY h.id DESC LIMIT 300')->fetchAll();
 $servers=db()->query('SELECT * FROM server_nodes ORDER BY name')->fetchAll();
}catch(Throwable $e){}
?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-page-head"><div><h2>Hosting / Sunucu / Panel Yönetimi Pro</h2><p>Sunucu seçimi, paket eşleştirme, yüzdelik kaynak kullanımı ve panel şifre senkronizasyonu.</p></div><a class="ao-btn soft" href="<?= url('admin/hosting-server/servers') ?>">Sunucular</a></div>
<div class="ao-card"><h3>Hosting Hesapları</h3>
<?php foreach($rows as $h): $metrics=ao_hosting_metric_rows($h); $pkgMatch=trim((string)($h['package_name']??''))!=='' && mb_strtolower(trim((string)$h['package_name']),'UTF-8')===mb_strtolower(trim((string)($h['product_name']??'')),'UTF-8'); ?>
 <div class="ao-hosting-admin-card">
  <div class="ao-hosting-admin-top"><div><h3>#<?= (int)$h['service_id'] ?> <?= e($h['domain'] ?: $h['service_domain'] ?? '') ?></h3><p><?= e(trim(($h['first_name']??'').' '.($h['last_name']??''))) ?> · <?= e($h['email']??'') ?> · Durum: <b><?= e(ao_status_tr($h['service_status'] ?? '')) ?></b></p><div class="ao-package-match"><span class="<?= $pkgMatch?'':'mismatch' ?>"><?= $pkgMatch?'Paket eşleşti':'Paket eşleşmedi' ?></span><span>Sunucu paketi: <?= e($h['package_name'] ?: '-') ?></span><span>Ahost paketi: <?= e($h['product_name'] ?: '-') ?></span></div></div><div><b><?= e($h['server_name'] ?: '-') ?></b><br><small><?= e($h['server_ip'] ?: '-') ?></small></div></div>
  <div class="ao-hosting-metrics-grid"><?php foreach($metrics as $m): $cls=$m['percent']>=90?'is-danger':($m['percent']>=75?'is-warn':''); ?><div class="ao-hosting-metric <?= $cls ?>"><div class="metric-head"><span><?= e($m['label']) ?></span><i><?= e($m['icon']) ?></i></div><strong><?= (int)$m['percent'] ?>%</strong><div class="ao-hosting-bar"><span style="width:<?= (int)$m['percent'] ?>%"></span></div><small><?= e($m['used']) ?> / <?= e($m['limit'] ?: '∞') ?> <?= e($m['unit']) ?> · Kalan: <?= e($m['limit'] ? $m['left'] : '∞') ?></small></div><?php endforeach; ?></div>
  <form method="post" action="<?= url('admin/hosting-server/account-action') ?>" class="ao-hosting-admin-form" data-password-tool><?= csrf_field() ?><input type="hidden" name="service_id" value="<?= (int)$h['service_id'] ?>"><input type="hidden" name="back" value="admin/hosting-server/accounts"><select name="server_id"><option value="">Sunucu seç / mevcut: <?= e($h['server_name'] ?: '-') ?></option><?php foreach($servers as $srv): ?><option value="<?= (int)$srv['id'] ?>"><?= e($srv['name']) ?> <?= e($srv['ip_address'] ?? '') ?></option><?php endforeach; ?></select><input name="package_name" value="<?= e($h['package_name'] ?: '') ?>" placeholder="Paket adı"><input type="password" name="panel_password" value="<?= e($h['panel_password'] ?: '') ?>" placeholder="Panel şifresi"><button type="button" class="ao-mini-btn" data-toggle-password>Göster</button><button type="button" class="ao-mini-btn" data-generate-password>Üret</button><select name="action"><option value="change-password">Şifre Değiştir</option><option value="change-package">Paket Değiştir</option><option value="move-server">Sunucu Taşı</option><option value="suspend">Suspend</option><option value="unsuspend">Unsuspend</option><option value="terminate">Terminate</option></select><button class="ao-hosting-action-btn primary">Uygula</button></form>
  <div class="ao-hosting-admin-actions"><a class="ao-mini-btn" target="_blank" href="<?= url('admin/service-panel-login?service_id='.(int)$h['service_id'].'&panel=cpanel') ?>">cPanel</a><a class="ao-mini-btn" target="_blank" href="<?= url('admin/service-panel-login?service_id='.(int)$h['service_id'].'&panel=webmail') ?>">Webmail</a><a class="ao-mini-btn" target="_blank" href="<?= url('admin/service-panel-login?service_id='.(int)$h['service_id'].'&panel=whm') ?>">WHM</a></div>
 </div>
<?php endforeach; if(!$rows): ?><div class="ao-empty">Hosting hesabı bulunamadı.</div><?php endif; ?>
</div>
<script id="aoHostingAdminPasswordToolV2469">
(function(){function gen(){var c='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%';var p='';for(var i=0;i<16;i++)p+=c[Math.floor(Math.random()*c.length)];return p;}document.addEventListener('click',function(e){var t=e.target.closest('[data-toggle-password]');if(t){var f=t.closest('[data-password-tool]'),i=f&&f.querySelector('input[name="panel_password"]');if(i){i.type=i.type==='password'?'text':'password';t.textContent=i.type==='password'?'Göster':'Gizle';}}var g=e.target.closest('[data-generate-password]');if(g){var f2=g.closest('[data-password-tool]'),i2=f2&&f2.querySelector('input[name="panel_password"]');if(i2){i2.type='text';i2.value=gen();var b=f2.querySelector('[data-toggle-password]');if(b)b.textContent='Gizle';}}});})();
</script>
