<?php
if (!function_exists('ao_settings_sections')) {
function ao_settings_sections(){ return [
 'general'=>['Genel','Firma, site URL, logo, canlı/test, bakım ve SEO ayarları.'],
 'localization'=>['Yerelleştirme','Dil, ülke, tarih, saat, telefon ve para birimi ayarları.'],
 'orders'=>['Sipariş Ayarları','Sepet, yenileme, sözleşme, çapraz satış ve sipariş akışları.'],
 'domain'=>['Domain Center','Registrar, nameserver, WHOIS, IDN ve domain yenileme ayarları.'],
 'mail'=>['E-Posta & SMTP','SMTP, gönderen bilgileri, imza, header/footer ve test gönderimi.'],
 'support'=>['Destek Merkezi','Ticket maskesi, departman görünümü, bilgi bankası ve ek dosya ayarları.'],
 'invoice'=>['Fatura & Muhasebe','Fatura numarası, PDF, gecikme bedeli, vergi ve e-fatura ayarları.'],
 'credit'=>['Kredi Sistemi','Müşteri bakiye/kredi ekleme limitleri ve onay akışı.'],
 'affiliate'=>['Satış Ortaklığı','Komisyon, bonus, minimum ödeme ve affiliate link ayarları.'],
 'security'=>['Güvenlik Merkezi','2FA, e-posta doğrulama, reCAPTCHA, IP, CSRF ve API güvenliği.'],
 'header'=>['Üst Bar & Duyuru','Duyuru alanı, kur gösterimi, dil seçimi, sepet, bildirim ve üst bar görünümü.'],
 'social'=>['Sosyal Medya','Facebook, Instagram, WhatsApp, YouTube, LinkedIn ve diğer sosyal bağlantılar.'],
 'ai'=>['AI Center','AI sağlayıcıları, API key rehberi, model seçimi ve bağlantı testleri.'],
 'license'=>['Lisans Merkezi','SiteBuilder, MobileBuilder, AI ve premium modül lisans ayarları.'],
 'notifications'=>['Bildirim Merkezi','Mail, SMS, WhatsApp ve olay bazlı bildirim ayarları.'],
 'sitebuilder'=>['SiteBuilder','Builder yayınlama, tema, header/footer ve SEO varsayılanları.'],
 'mobilebuilder'=>['MobileBuilder','Build Center, Android paket adı, keystore ve APK/AAB ayarları.'],
 'setup'=>['Kurulum Sihirbazı','Kurulum tamamlama merkezi ve eksik alan kontrolü.'],
 'health'=>['Sistem Sağlığı','PHP, MySQL, cron, SSL, SMTP, ödeme, registrar ve AI kontrolleri.']
 ]; }
function ao_setting_specs($section){
 $s=[
  'general'=>[
   ['company_name','Firma Adı','text','Ahost One'],['company_email','Firma E-posta','email','info@example.com'],['company_phone','Telefon','text','+90'],['site_url','Site URL','url','https://example.com'],['logo_url','Logo / Dosya URL','text',''],['favicon_url','Favicon / Dosya URL','text',''],['production_mode','Çalışma Ortamı','select','0',['0'=>'Test Ortamı / Sandbox','1'=>'Canlı Ortam / Production']],['demo_data_enabled','Demo Veriler','select','0',['0'=>'Kapalı','1'=>'Açık']],['force_https','HTTPS Zorunlu','switch','0'],['maintenance_mode','Bakım Modu','switch','0'],['maintenance_message','Bakım Modu Mesajı','textarea','Şu anda bakım yapıyoruz ve kısa süre sonra geri döneceğiz.'],['maintenance_redirect_url','Bakımda URL Yönlendirme','url',''],['seo_friendly_url','SEO Dostu URL','select','full',['full'=>'Full SEO Dostu URL','basic'=>'Temel SEO URL','off'=>'Kapalı']],['activity_log_limit','Etkinlik Günlüğü Limiti','number','10000'],['records_per_page','Sayfa Başına Kayıt','number','50'] ],
  'localization'=>[
   ['charset','Sistem Karakter Seti','text','utf-8'],['date_format','Tarih Formatı','select','d/m/Y',['d/m/Y'=>'DD/MM/YYYY','m/d/Y'=>'MM/DD/YYYY','Y-m-d'=>'YYYY-MM-DD']],['client_date_format','Müşteri Tarih Formatı','select','default',['default'=>'Genel tarih biçimini kullan','long'=>'Uzun tarih','short'=>'Kısa tarih']],['default_country','Varsayılan Ülke','text','Turkey'],['default_language','Varsayılan Dil','select','tr',['tr'=>'Türkçe','en'=>'English']],['language_menu_enabled','Dil Menüsünü Etkinleştir','switch','1'],['dynamic_field_translation','Dinamik Alan Tercümesi','switch','0'],['utf8_mail_header','Genişletilmiş UTF-8 Karakterleri Kaldır','switch','1'],['international_phone_enabled','Telefon Numaraları','switch','1'],['default_currency','Varsayılan Para Birimi','select','TRY',['TRY'=>'Türk Lirası','USD'=>'USD','EUR'=>'EUR']],['tcmb_cron_enabled','TCMB Kur Cron','switch','0'] ],
  'orders'=>[
   ['pre_payment_days','Ödeme Tarihi Öncesi Ödeme','number','0'],['order_template','Varsayılan Sipariş Şablonu','select','modern',['modern'=>'Ahost Modern','comparison'=>'Karşılaştırma','cart'=>'Standart Sepet']],['early_renewal_enabled','İsteğe Bağlı Yenilemeler','switch','1'],['renew_monthly_days','Aylık Yenileme Gün Sınırı','number','31'],['renew_yearly_days','Yıllık Yenileme Gün Sınırı','number','731'],['sidebar_cart_closed','Kenar Çubuğunu Kapat','switch','0'],['tos_required','Kullanım Şartları Zorunlu','switch','1'],['tos_url','Kullanım Şartları URL','url','/sartlar'],['auto_redirect_after_payment','Ödemede Otomatik Yönlendir','select','invoice',['invoice'=>'Faturaya yönlendir','client'=>'Müşteri paneline yönlendir','none'=>'Yönlendirme yok']],['allow_order_notes','Sipariş Notları','switch','1'],['allow_multi_domain_order','Çoklu Domain Siparişi','switch','1'],['manual_review_new_orders','Yeni Siparişleri Manuel Onaya Al','switch','0'],['cross_sell_enabled','Ürün Çapraz Satışı','switch','1'],['cross_sell_count','Çapraz Satış Sayısı','number','10'] ],
  'domain'=>[
   ['allow_domain_register','Alan Adı Kaydı','switch','1'],['allow_domain_transfer','Alan Adı Transferi','switch','1'],['allow_own_domain','Kendi Alan Adını Kullan','switch','1'],['domain_renewal_orders','Yenileme Siparişleri','switch','1'],['auto_domain_renewal','Otomatik Yenileme','switch','1'],['default_auto_renew','Varsayılan Otomatik Yenileme','switch','1'],['idn_enabled','IDN Domain','switch','1'],['domain_due_invoice_mode','Alan Adı Ödeme ve Geri Ödeme Ücretleri','select','append',['append'=>'Mevcut faturaya ekle','new'=>'Yeni fatura oluştur']],['default_nameserver1','Varsayılan Nameserver 1','text','ns1.example.com'],['default_nameserver2','Varsayılan Nameserver 2','text','ns2.example.com'],['default_nameserver3','Varsayılan Nameserver 3','text',''],['default_nameserver4','Varsayılan Nameserver 4','text',''],['default_nameserver5','Varsayılan Nameserver 5','text',''],['domain_contact_use_client','Müşteri Detaylarını Kullan','switch','1'] ],
  'mail'=>[
   ['mail_provider','Posta Sağlayıcı','select','smtp',['smtp'=>'SMTP','phpmail'=>'PHP Mail']],['mail_disable_send','E-posta Göndermeyi Devre Dışı Bırak','switch','0'],['mail_disable_rfc3834','RFC3834 Başlıklarını Devre Dışı Bırak','switch','0'],['email_signature','Genel E-posta İmzası','textarea','Ahost One'],['email_css','E-posta CSS Biçimlendirmesi','textarea',''],['email_header_html','Müşteri E-posta Header İçeriği','textarea',''],['email_footer_html','Müşteri E-posta Footer İçeriği','textarea',''],['system_email_sender_name','Sistem E-postaları Gönderen Adı','text','Ahost One'],['system_email_sender_email','Sistem E-postaları Gönderen Adresi','email','noreply@example.com'],['bcc_messages','BCC Mesajlar','text',''],['presales_form_target','Ön Satış Form Hedefi','text',''],['presales_email','Ön Satış İletişim Formu E-postası','email',''] ],
  'support'=>[
   ['support_module','Destek Modülü','select','internal',['internal'=>'Ahost One Dahili Sistem','external'=>'Harici Destek Sistemi']],['ticket_mask','Destek Talebi Maskeleme Biçimi','text','%A%A%A-%n%n%n%n%n%n'],['ticket_list_order','Destek Talebi Cevap Listesi','select','asc',['asc'=>'Artan','desc'=>'Azalan']],['ticket_email_limit','E-posta Talep Yanıtlama Limiti','number','10'],['show_client_departments','Müşterilere Özel Departmanları Göster','switch','1'],['ticket_reply_redirect','Müşteri Destek Talebi Girişi Gerekir','switch','1'],['kb_suggestions','Bilgi Bankası Önerileri','switch','1'],['ticket_attachments','Ek Türleri','text','.jpg,.gif,.jpeg,.png,.txt,.pdf'],['service_status_required','Hizmet Durumu Giriş Gerektirsin','switch','1'],['reopen_imported_tickets','İçe Aktarma Başarılı Olursa Mevcut Biletleri Yeniden Aç','switch','1'] ],
  'invoice'=>[
   ['continuous_invoice_generation','Devam Eden Fatura Oluşturma','switch','0'],['metric_invoicing_enabled','Metrik Kullanım Faturalandırması','switch','1'],['pdf_invoice_enabled','PDF Faturaları Etkinleştir','switch','1'],['pdf_paper_size','PDF Kağıt Boyu','select','A4',['A4'=>'A4','Letter'=>'Letter']],['pdf_font','PDF Font Tipi','select','dejavusans',['dejavusans'=>'DejavuSans','helvetica'=>'Helvetica','times'=>'Times']],['client_invoice_delete','Müşteri Verisini Devre Dışı Bırak','switch','1'],['mass_payment_enabled','Toplu Ödemeyi Etkinleştir','switch','1'],['late_fee_type','Gecikme Ücreti Tipi','select','fixed',['fixed'=>'Sabit Tutar','percent'=>'Yüzde']],['late_fee_amount','Gecikme Ücreti Tutarı','number','10.00'],['min_late_fee','Minimum Geç Ücret','number','0.00'],['invoice_number_format','Sıralı Fatura Numara Formatı','text','{NUMBER}'],['next_paid_invoice_number','Sonraki Ödenmiş Fatura Numarası','number','1'],['invoice_increment','Fatura No Artışı','number','1'],['invoice_starting_number','Fatura Başlangıcı','number',''] ],
  'credit'=>[
   ['credit_enabled','Etkinleştir / Devredışı Bırak','switch','1'],['min_credit','Minimum Kredi','number','50.00'],['max_credit','Maksimum Kredi','number','1000.00'],['max_credit_balance','Maksimum Bakiye','number','3000.00'],['credit_requires_approval','Aktif Sipariş Gerektir','switch','1'],['auto_apply_credit','Otomatik Kredi Kullanımı','switch','1'],['add_credit_to_refunds','Düşürmelerde Kredi Ekle','switch','1'] ],
  'affiliate'=>[
   ['affiliate_enabled','Etkinleştir / Devredışı Bırak','switch','0'],['affiliate_commission_percent','Satış Ortaklığı Kazanç Yüzdesi','number','15'],['affiliate_bonus','Satış Ortaklığı Bonus Kredi','number','0.00'],['affiliate_min_withdraw','Satış Ortaklığı Ödeme Miktarı','number','25.00'],['affiliate_payout_delay','Komisyon Ödemesi Erteleme','number','15'],['affiliate_payout_department','Ödeme Talep Departmanı','text',''],['affiliate_links','Satış Ortaklığı Linkleri','textarea',''] ],
  'security'=>[
   ['email_verification_required','E-posta Doğrulama','switch','1'],['admin_mfa_policy','Admin 2FA Politikası','select','optional',['off'=>'Kapalı','optional'=>'İsteğe Bağlı','required'=>'Zorunlu']],['customer_mfa_policy','Müşteri 2FA Politikası','select','optional',['off'=>'Kapalı','optional'=>'İsteğe Bağlı','required'=>'Zorunlu']],['mfa_default_method','Varsayılan 2FA Yöntemi','select','mail',['mail'=>'Mail OTP','totp'=>'Google Authenticator','sms'=>'SMS OTP']],['mfa_mail_enabled','Mail OTP','switch','1'],['mfa_totp_enabled','Google Authenticator','switch','1'],['mfa_sms_enabled','SMS OTP','switch','0'],['mfa_otp_ttl_minutes','OTP Süresi (dakika)','number','5'],['mfa_max_attempts','Maksimum OTP Denemesi','number','5'],['captcha_forms','Captcha Form Koruması','select','login',['off'=>'Kapalı','login'=>'Girişte','always'=>'Her zaman']],['captcha_type','Güvenlik Kodu Tipi','select','recaptcha2',['recaptcha2'=>'reCAPTCHA v2','recaptcha3'=>'reCAPTCHA v3','turnstile'=>'Cloudflare Turnstile']],['recaptcha_site_key','reCAPTCHA Site Anahtarı','text',''],['recaptcha_secret_key','reCAPTCHA Secret Anahtarı','password',''],['password_strength','Gerekli Şifre Uzunluğu','number','8'],['failed_login_limit','Başarısız Admin Giriş Denemesi Sınırı','number','5'],['ip_ban_enabled','IP Ban','switch','1'],['csrf_admin_enabled','CSRF Token Admin','switch','1'],['csrf_client_enabled','CSRF Token Müşteri','switch','1'],['api_ip_restriction','API IP Erişim Kısıtlaması','textarea',''] ],
  'header'=>[
   ['site_announcement_enabled','Duyuru Alanı Aktif','switch','1'],['site_announcement_text','Duyuru Metni','textarea','Ahost One v22.1.0 ile SiteBuilder, MobileBuilder ve Marketplace yenilendi.'],['site_announcement_url','Duyuru Linki','url',''],['site_announcement_style','Duyuru Stili','select','info',['info'=>'Bilgi','success'=>'Başarı','warning'=>'Uyarı','danger'=>'Kritik']],['site_announcement_start','Başlangıç Tarihi','text',''],['site_announcement_end','Bitiş Tarihi','text',''],['topbar_currency_enabled','Kur Bilgisi Göster','switch','1'],['usd_try_rate','USD/TRY Kur','number','45.00'],['currency_margin_percent','Kur Marjı %','number','0'],['language_menu_enabled','Dil Seçimi Göster','switch','1'],['enabled_languages','Aktif Diller','text','tr,en'],['topbar_notifications_enabled','Müşteri Bildirim İkonu','switch','1'],['topbar_cart_enabled','Sepet İkonu','switch','1'],['topbar_social_enabled','Sosyal Ağ İkonları','switch','1'] ],
  'social'=>[
   ['facebook','Facebook','text',''],['instagram','Instagram','text',''],['linkedin','LinkedIn','text',''],['twitter','X / Twitter','text',''],['tiktok','TikTok','text',''],['youtube','YouTube','text',''],['whatsapp','WhatsApp','text',''],['telegram','Telegram','text',''],['github','GitHub','text',''],['discord','Discord','text',''],['share_tweet_enabled','Duyurularda Tweet','switch','0'],['facebook_recommend_enabled','Facebook Tavsiyeler','switch','0'],['facebook_comments_enabled','Facebook Yorumları','switch','0'] ],
  'ai'=>[
   ['ai_enabled','AI Center Etkin','switch','1'],['default_ai_provider','Varsayılan Sağlayıcı','select','openai',['openai'=>'OpenAI','gemini'=>'Gemini','claude'=>'Claude','deepseek'=>'DeepSeek','grok'=>'Grok']],['default_ai_model','Varsayılan Model','text',''],['openai_api_key','OpenAI API Key','password',''],['gemini_api_key','Gemini API Key','password',''],['claude_api_key','Claude API Key','password',''],['deepseek_api_key','DeepSeek API Key','password',''],['grok_api_key','Grok API Key','password',''],['ai_help_guides_enabled','API Key Alma Rehberi','switch','1'],['ai_connection_test_enabled','Bağlantı Testi','switch','1'] ],
  'license'=>[
   ['license_center_enabled','Lisans Merkezi Etkin','switch','1'],['license_server_url','Lisans Sunucu URL','url',''],['purchase_code_required','Purchase Code Zorunlu','switch','0'],['sitebuilder_license_required','SiteBuilder Lisansı','switch','0'],['mobilebuilder_license_required','MobileBuilder Lisansı','switch','0'],['ai_license_required','AI Lisansı','switch','0'],['premium_modules_license_required','Premium Modül Lisansı','switch','0'] ],
  'notifications'=>[
   ['mail_notifications_enabled','Mail Bildirimleri','switch','1'],['sms_notifications_enabled','SMS Bildirimleri','switch','0'],['whatsapp_notifications_enabled','WhatsApp Bildirimleri','switch','0'],['notify_order','Sipariş Bildirimi','switch','1'],['notify_invoice','Fatura Bildirimi','switch','1'],['notify_domain_renewal','Domain Yenileme Bildirimi','switch','1'],['notify_ticket','Ticket Bildirimi','switch','1'],['notify_service_suspend','Hosting Askıya Alma Bildirimi','switch','1'],['notification_webhook_url','Genel Webhook URL','url',''] ],
  'sitebuilder'=>[
   ['sitebuilder_enabled','SiteBuilder Etkin','switch','1'],['sitebuilder_default_theme','Varsayılan Tema','text','default'],['sitebuilder_header_builder','Header Builder','switch','1'],['sitebuilder_footer_builder','Footer Builder','switch','1'],['sitebuilder_seo_defaults','SEO Varsayılanları','switch','1'],['sitebuilder_frontend_edit','Frontend Düzenleme','switch','1'],['sitebuilder_backup_before_publish','Yayın Öncesi Yedek','switch','1'] ],
  'mobilebuilder'=>[
   ['mobilebuilder_enabled','MobileBuilder Etkin','switch','1'],['build_center_enabled','Build Center Etkin','switch','1'],['android_package_prefix','Android Paket Prefix','text','com.ahostone.app'],['default_keystore_alias','Varsayılan Keystore Alias','text',''],['apk_storage_path','APK/AAB Depolama Yolu','text','storage/builds'],['remote_build_node_enabled','Remote Build Node','switch','0'],['remote_build_node_url','Remote Build Node URL','url',''] ],
  'setup'=>[
   ['setup_wizard_enabled','Kurulum Sihirbazı Etkin','switch','1'],['setup_wizard_completed','Kurulum Tamamlandı','switch','0'],['setup_require_logo','Logo Zorunlu','switch','1'],['setup_require_smtp','SMTP Zorunlu','switch','1'],['setup_require_payment','Ödeme Zorunlu','switch','1'],['setup_require_registrar','Registrar Zorunlu','switch','1'],['setup_require_ai','AI Center Zorunlu','switch','0'] ],
  'health'=>[
   ['health_cron_enabled','Cron Kontrolü','switch','1'],['health_ssl_check_enabled','SSL Kontrolü','switch','1'],['health_smtp_check_enabled','SMTP Kontrolü','switch','1'],['health_payment_check_enabled','Ödeme Kontrolü','switch','1'],['health_registrar_check_enabled','Registrar Kontrolü','switch','1'],['health_ai_check_enabled','AI Sağlayıcı Kontrolü','switch','1'],['health_report_email','Sağlık Raporu E-postası','email',''] ]
 ]; return $s[$section] ?? $s['general']; }
function ao_render_settings_nav($active){ echo '<div class="ao-settings-grid">'; foreach(ao_settings_sections() as $key=>$info){ $cls=$key===$active?' active':''; echo '<a class="ao-setting-card'.$cls.'" href="'.url('admin/settings/'.$key).'"><b>'.e($info[0]).'</b><span>'.e($info[1]).'</span></a>'; } echo '</div>'; }
function ao_setting_input($spec){ [$key,$label,$type,$default]=$spec; $opts=$spec[4]??[]; $val=admin_setting($key,$default); echo '<label class="ao-field"><span>'.e($label).'</span>'; if($type==='textarea'){ echo '<textarea name="settings['.e($key).']" rows="4">'.e($val).'</textarea>'; } elseif($type==='select'){ echo '<select name="settings['.e($key).']">'; foreach($opts as $k=>$v) echo '<option value="'.e($k).'" '.((string)$val===(string)$k?'selected':'').'>'.e($v).'</option>'; echo '</select>'; } elseif($type==='switch'){ echo '<input type="hidden" name="settings['.e($key).']" value="0"><label class="ao-switch"><input type="checkbox" name="settings['.e($key).']" value="1" '.((string)$val==='1'?'checked':'').'><i></i><em>'.((string)$val==='1'?'Açık':'Kapalı').'</em></label>'; } elseif($type==='password'){ echo '<div class="ao-secret"><input type="password" name="settings['.e($key).']" value="'.e($val).'" autocomplete="new-password"><button type="button" onclick="const i=this.previousElementSibling;i.type=i.type===\'password\'?\'text\':\'password\'">Göster</button></div>'; } else { echo '<input type="'.e($type).'" name="settings['.e($key).']" value="'.e($val).'">'; } echo '</label>'; }
}
?>
