<?php $tabs=[
 'general'=>'Genel','localization'=>'Yerelleştirme','order'=>'Sipariş','domain'=>'Domain','smtp'=>'SMTP','finance'=>'Finans','security'=>'Güvenlik','notifications'=>'Bildirimler','support'=>'Destek','social'=>'Sosyal Medya','ai'=>'AI Center','sitebuilder'=>'SiteBuilder','mobilebuilder'=>'MobileBuilder','marketplace'=>'Marketplace','license'=>'Lisans'
]; ?>
<div class="ao-admin-page-head"><div><span>Settings Center</span><h1>Ayarlar Merkezi</h1><p>Site, sipariş, ödeme, domain, güvenlik, bildirim, builder ve marketplace ayarlarını sekmeli şekilde yönetin.</p></div><button form="settingsForm" class="ao-btn ao-btn--primary">Kaydet</button></div>
<form id="settingsForm" method="post" action="<?= url('admin/settings/save') ?>" class="ao-tab-shell ao-admin-card" data-ao-tabs><?= csrf_field() ?>
  <div class="ao-tabs"><?php $first=true; foreach($tabs as $k=>$t): ?><button type="button" class="<?= $first?'active':'' ?>" data-tab-target="<?= e($k) ?>"><?= e($t) ?></button><?php $first=false; endforeach; ?></div>
  <section class="ao-tab-panel active" data-tab-pane="general"><h2>Genel</h2><div class="ao-form-grid"><label>Site Adı<input name="settings[site_name]" value="<?= e(admin_setting('site_name','Ahost One')) ?>"></label><label>Site URL<input name="settings[site_url]" value="<?= e(admin_setting('site_url',url(''))) ?>"></label><label>Logo URL<input name="settings[logo_url]" value="<?= e(admin_setting('logo_url','')) ?>"></label><label>Admin E-posta<input name="settings[admin_email]" value="<?= e(admin_setting('admin_email','')) ?>"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="localization"><h2>Yerelleştirme</h2><div class="ao-form-grid"><label>Varsayılan Dil<select name="settings[default_lang]"><option>Türkçe</option><option>English</option></select></label><label>Para Birimi<select name="settings[currency]"><option>TRY</option><option>USD</option><option>EUR</option></select></label><label>Kur Gösterimi<input name="settings[currency_preview]" value="1 $ = 47.25 TL"></label><label>Tarih Formatı<input name="settings[date_format]" value="d.m.Y"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="order"><h2>Sipariş</h2><div class="ao-form-grid"><label>Sipariş Onayı<select name="settings[order_approval]"><option>Otomatik</option><option>Manuel</option></select></label><label>Sepet Hatırlatma<select name="settings[cart_reminder]"><option>Aktif</option><option>Pasif</option></select></label><label>Minimum Sepet<input name="settings[min_cart]" value="0"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="domain"><h2>Domain</h2><div class="ao-form-grid"><label>Varsayılan Registrar<select name="settings[default_registrar]"><option>DomainNameAPI</option></select></label><label>Auto-renew<select name="settings[domain_auto_renew]"><option>Aktif</option><option>Pasif</option></select></label><label>Yenileme Uyarısı Gün<input name="settings[domain_expire_warning_days]" value="30"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="smtp"><h2>SMTP</h2><div class="ao-form-grid"><label>SMTP Host<input name="settings[smtp_host]"></label><label>Port<input name="settings[smtp_port]" value="587"></label><label>Kullanıcı<input name="settings[smtp_user]"></label><label>Şifre<input type="password" name="settings[smtp_pass]"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="finance"><h2>Finans</h2><div class="ao-form-grid"><label>Vergi Oranı<input name="settings[tax_rate]" value="20"></label><label>Fatura Prefix<input name="settings[invoice_prefix]" value="INV"></label><label>Hatırlatma<select name="settings[invoice_reminder]"><option>Aktif</option><option>Pasif</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="security"><h2>Güvenlik</h2><div class="ao-form-grid"><label>Admin MFA<select name="settings[admin_mfa_policy]"><option value="optional">İsteğe Bağlı</option><option value="required">Zorunlu</option></select></label><label>Müşteri MFA<select name="settings[customer_mfa_policy]"><option value="optional">İsteğe Bağlı</option><option value="required">Zorunlu</option></select></label><label>reCAPTCHA Site Key<input name="settings[recaptcha_site_key]"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="notifications"><h2>Bildirimler</h2><div class="ao-form-grid"><label>Mail<select name="settings[notify_email_enabled]"><option>Aktif</option><option>Pasif</option></select></label><label>SMS<select name="settings[notify_sms_enabled]"><option>Aktif</option><option>Pasif</option></select></label><label>WhatsApp<select name="settings[notify_whatsapp_enabled]"><option>Aktif</option><option>Pasif</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="support"><h2>Destek</h2><div class="ao-form-grid"><label>WhatsApp<input name="settings[support_whatsapp_number]"></label><label>Telefon<input name="settings[support_call_number]"></label><label>AI Destek<select name="settings[support_ai_enabled]"><option>Aktif</option><option>Pasif</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="social"><h2>Sosyal Medya</h2><div class="ao-form-grid"><label>Facebook<input name="settings[social_facebook]"></label><label>Instagram<input name="settings[social_instagram]"></label><label>X / Twitter<input name="settings[social_x]"></label><label>LinkedIn<input name="settings[social_linkedin]"></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="ai"><h2>AI Center</h2><div class="ao-form-grid"><label>OpenAI API Key<input name="settings[openai_api_key]"></label><label>Gemini API Key<input name="settings[gemini_api_key]"></label><label>Claude API Key<input name="settings[claude_api_key]"></label><label>Varsayılan Sağlayıcı<select name="settings[default_ai_provider]"><option>openai</option><option>gemini</option><option>claude</option><option>custom</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="sitebuilder"><h2>SiteBuilder</h2><div class="ao-form-grid"><label>AI Tasarım<select name="settings[sitebuilder_ai_edit]"><option>Aktif</option><option>Pasif</option></select></label><label>ZIP Export<select name="settings[sitebuilder_zip_export]"><option>Aktif</option><option>Pasif</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="mobilebuilder"><h2>MobileBuilder</h2><div class="ao-form-grid"><label>AI Uygulama<select name="settings[mobilebuilder_ai_edit]"><option>Aktif</option><option>Pasif</option></select></label><label>Build Queue<select name="settings[mobilebuilder_build_queue]"><option>Aktif</option><option>Pasif</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="marketplace"><h2>Marketplace</h2><div class="ao-form-grid"><label>Komisyon %<input name="settings[marketplace_commission]" value="10"></label><label>Escrow<select name="settings[marketplace_escrow_enabled]"><option>Aktif</option><option>Pasif</option></select></label></div></section>
  <section class="ao-tab-panel" data-tab-pane="license"><h2>Lisans</h2><div class="ao-form-grid"><label>Trial Lisans<select name="settings[trial_license_enabled]"><option>Aktif</option><option>Pasif</option></select></label><label>Trial Gün<input name="settings[trial_days]" value="14"></label></div></section>
</form>
