<?php
try{$rules=db()->query('SELECT * FROM automation_rules ORDER BY id DESC')->fetchAll();}catch(Throwable $e){$rules=[];}
$templates=[['Fatura Hatırlatma','invoice.due_soon','send_notification'],['Sipariş Onayı','order.paid','activate_service'],['WHM Kurulum','hosting.order_approved','create_hosting'],['Suspend','invoice.overdue','suspend_service'],['Domain Yenileme','domain.expiring','send_notification'],['Yarım Sepet','cart.abandoned','send_coupon'],['Ticket Bildirimi','ticket.created','notify_department']];
?>
<div class="ao-hero-slim"><div class="cp-page-head"><div><h2>Otomasyonlar</h2><p>Fatura, sipariş, hosting, domain, sepet ve ticket olayları için kural motoru.</p></div><button class="ao-btn" type="button" data-ao-tab="new" onclick="document.querySelector('[data-ao-tab=new]')?.click()">+ Kural Ekle</button></div></div>
<div class="rc7-metric-grid"><div class="rc7-metric"><span>⚙</span><small>Toplam Kural</small><strong><?= count($rules) ?></strong></div><div class="rc7-metric"><span>✅</span><small>Aktif</small><strong><?= count(array_filter($rules,fn($r)=>!empty($r['is_active']))) ?></strong></div><div class="rc7-metric"><span>📈</span><small>Bu Ay Çalışma</small><strong>0</strong></div><div class="rc7-metric"><span>⚠</span><small>Hata</small><strong>0</strong></div></div>
<div class="ao-card" data-ao-tabs><div class="ao-panel-tabs"><button class="active" data-ao-tab="list">Kurallar</button><button data-ao-tab="new">Yeni Kural</button><button data-ao-tab="tpl">Hazır Şablonlar</button><button data-ao-tab="log">Log</button></div>
<section class="ao-panel active" data-ao-panel="list"><h3>Otomasyon Kuralları</h3><div class="ao-table-wrap"><table class="ao-table"><thead><tr><th>Kural</th><th>Tetikleyici</th><th>Koşul</th><th>Aksiyon</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><?php foreach($rules as $r): ?><tr><td><strong><?= e($r['name']) ?></strong></td><td><code><?= e($r['trigger_event']??$r['event_name']??'') ?></code></td><td><?= e($r['condition_json']??'-') ?></td><td><code><?= e($r['action_type']??$r['action_name']??'') ?></code></td><td><span class="ao-pill <?= !empty($r['is_active'])?'green':'red' ?>"><?= !empty($r['is_active'])?'Aktif':'Pasif' ?></span></td><td class="ao-action-row"><a class="ao-btn small" href="<?= url('admin/automation/toggle?id='.(int)$r['id'].'&csrf_token='.csrf_token()) ?>">Aktif/Pasif</a><a class="ao-btn small ao-mini-danger" data-confirm="Kural silinsin mi?" href="<?= url('admin/automation/delete?id='.(int)$r['id'].'&csrf_token='.csrf_token()) ?>">Sil</a></td></tr><?php endforeach; if(!$rules): ?><tr><td colspan="6">Henüz kural tanımlanmadı.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="ao-panel" data-ao-panel="new"><h3>Yeni Kural</h3><form method="post" action="<?= url('admin/automation/save') ?>" class="ao-form ao-form-grid"><?= csrf_field() ?><label>Kural Adı<input name="name" required placeholder="Fatura 7 gün önce hatırlatma"></label><label>Tetikleyici<select name="trigger_event"><option value="invoice.due_soon">Fatura yaklaşınca</option><option value="invoice.overdue">Fatura gecikince</option><option value="order.paid">Sipariş ödenince</option><option value="hosting.order_approved">Hosting onaylanınca</option><option value="domain.expiring">Domain süresi yaklaşınca</option><option value="cart.abandoned">Yarım sepet oluşunca</option><option value="ticket.created">Ticket açılınca</option></select></label><label>Aksiyon<select name="action_type"><option value="send_notification">Bildirim gönder</option><option value="create_ticket">Ticket aç</option><option value="activate_service">Hizmeti aktif et</option><option value="suspend_service">Hizmeti askıya al</option><option value="create_hosting">WHM/cPanel kur</option><option value="send_coupon">Kupon gönder</option></select></label><label>Koşullar<textarea name="condition_json" placeholder='{"days":7}'></textarea></label><label>Aksiyon Ayarları<textarea name="action_json" placeholder='{"channel":"email,sms,whatsapp"}'></textarea></label><label><input type="checkbox" name="is_active" value="1" checked> Aktif</label><div><button class="ao-btn">Kuralı Kaydet</button></div></form></section>
<section class="ao-panel" data-ao-panel="tpl"><h3>Hazır Kural Şablonları</h3><?php foreach($templates as $t): ?><form method="post" action="<?= url('admin/automation/save') ?>" style="display:inline-block;margin:5px"><?= csrf_field() ?><input type="hidden" name="name" value="<?= e($t[0]) ?>"><input type="hidden" name="trigger_event" value="<?= e($t[1]) ?>"><input type="hidden" name="action_type" value="<?= e($t[2]) ?>"><input type="hidden" name="is_active" value="1"><button class="ao-btn soft"><?= e($t[0]) ?></button></form><?php endforeach; ?></section>
<section class="ao-panel" data-ao-panel="log"><h3>Otomasyon Log</h3><p class="ao-muted">Son çalışan kurallar ve hata kayıtları burada listelenir.</p></section>
</div>
