<?php
$flash = get_flash(); $orders=[]; $stats=['pending'=>0,'active'=>0,'cancelled'=>0,'fraud'=>0]; $viewOrder=null; $orderItems=[]; $invoice=null;
try{
 $orders=db()->query("SELECT o.*, c.first_name,c.last_name,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.id DESC LIMIT 300")->fetchAll();
 foreach($orders as $row){ if(isset($stats[$row['status']])) $stats[$row['status']]++; }
 if(!empty($_GET['view'])){ $q=db()->prepare("SELECT o.*,c.first_name,c.last_name,c.email,c.balance FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.id=?"); $q->execute([(int)$_GET['view']]); $viewOrder=$q->fetch(); if($viewOrder){ $i=db()->prepare('SELECT * FROM order_items WHERE order_id=?'); $i->execute([$viewOrder['id']]); $orderItems=$i->fetchAll(); $fq=db()->prepare('SELECT * FROM invoices WHERE order_id=? LIMIT 1'); $fq->execute([$viewOrder['id']]); $invoice=$fq->fetch(); }}
}catch(Throwable $e){}
?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<div class="ao-page-head"><div><h2>Siparişler Modülü Pro</h2><p>Sipariş yaşam döngüsü, fraud kontrol, fatura ilişkisi ve provisioning akışı.</p></div><a class="ao-btn" href="<?= url('admin/orders/new') ?>">+ Yeni Sipariş</a></div>
<div class="ao-stats-grid"><div class="ao-stat"><span>Bekleyen</span><strong><?= $stats['pending'] ?></strong></div><div class="ao-stat"><span>Aktif</span><strong><?= $stats['active'] ?></strong></div><div class="ao-stat"><span>İptal</span><strong><?= $stats['cancelled'] ?></strong></div><div class="ao-stat"><span>Fraud</span><strong><?= $stats['fraud'] ?></strong></div></div>
<?php if($viewOrder): ?>
<div class="ao-card">
 <div class="ao-page-head"><div><h3><?= e($viewOrder['order_number']) ?> Sipariş Detayı</h3><p><?= e($viewOrder['first_name'].' '.$viewOrder['last_name'].' - '.$viewOrder['email']) ?></p></div><div class="ao-actions no-margin"><a class="ao-mini-btn" href="<?= url('admin/orders/approve?id='.(int)$viewOrder['id']) ?>">Onayla / Provision</a><a class="ao-mini-btn" href="<?= url('admin/orders/fraud-clear?id='.(int)$viewOrder['id']) ?>">Fraud Temizle</a><a class="ao-mini-btn" style="color:#e53" href="<?= url('admin/orders/cancel?id='.(int)$viewOrder['id']) ?>">İptal</a></div></div>
 <div class="ao-grid two"><div><h4>Genel Bilgiler</h4><div class="ao-info-list"><p><b>Durum:</b> <?= e($viewOrder['status']) ?></p><p><b>Provision:</b> <?= e($viewOrder['provision_status']??'pending') ?></p><p><b>Fraud Skoru:</b> <?= (int)($viewOrder['fraud_score']??0) ?></p><p><b>Toplam:</b> <?= number_format((float)$viewOrder['total'],2,',','.') ?> ₺</p><p><b>Ödeme:</b> <?= e($viewOrder['payment_method']??'-') ?></p></div></div><div><h4>Fatura</h4><?php if($invoice): ?><p><b><?= e($invoice['invoice_number']) ?></b> - <?= e($invoice['status']) ?> - <?= number_format((float)$invoice['total'],2,',','.') ?> ₺</p><a class="ao-mini-btn" href="<?= url('admin/accounting/invoices?view='.(int)$invoice['id']) ?>">Faturaya Git</a><?php else: ?><p>Fatura henüz yok.</p><?php endif; ?></div></div>
 <h4>Ürünler / Domainler</h4><table class="ao-table"><thead><tr><th>Ürün</th><th>Tip</th><th>Domain</th><th>Periyot</th><th>Tutar</th><th>Modül</th></tr></thead><tbody><?php foreach($orderItems as $it): ?><tr><td><?= e($it['item_name']) ?></td><td><?= e($it['item_type']) ?></td><td><?= e($it['domain']) ?></td><td><?= e($it['billing_cycle']) ?></td><td><?= number_format((float)$it['price'],2,',','.') ?> ₺</td><td><?= e($it['module_name']) ?></td></tr><?php endforeach; ?></tbody></table>
</div>
<?php endif; ?>
<div class="ao-card"><h3>Sipariş Listesi</h3><table class="ao-table"><thead><tr><th>No</th><th>Müşteri</th><th>Tutar</th><th>Fraud</th><th>Provision</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><?php foreach($orders as $o): ?><tr><td><strong><?= e($o['order_number']) ?></strong></td><td><?= e(($o['first_name']??'').' '.($o['last_name']??'')) ?><br><small><?= e($o['email']??'') ?></small></td><td><?= number_format((float)$o['total'],2,',','.') ?> ₺</td><td><?= (int)($o['fraud_score']??0) ?></td><td><?= e($o['provision_status']??'pending') ?></td><td><span class="ao-badge <?= e($o['status']) ?>"><?= e($o['status']) ?></span></td><td><a class="ao-mini-btn" href="<?= url('admin/orders/view?id='.(int)$o['id']) ?>">Detay</a><?php if($o['status']==='pending'): ?> <a class="ao-mini-btn" href="<?= url('admin/orders/approve?id='.(int)$o['id']) ?>">Onayla</a><?php endif; ?></td></tr><?php endforeach; if(!$orders): ?><tr><td colspan="7">Sipariş yok.</td></tr><?php endif; ?></tbody></table></div>
