<?php
$flash=get_flash(); $id=(int)($_GET['id']??0); $o=null; $items=[]; $invoice=null; $logs=[];
try{ $q=db()->prepare('SELECT o.*, c.first_name,c.last_name,c.email,c.balance FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.id=? LIMIT 1'); $q->execute([$id]); $o=$q->fetch(); if($o){$it=db()->prepare('SELECT * FROM order_items WHERE order_id=?');$it->execute([$id]);$items=$it->fetchAll();$fq=db()->prepare('SELECT * FROM invoices WHERE order_id=? LIMIT 1');$fq->execute([$id]);$invoice=$fq->fetch(); try{$lg=db()->prepare('SELECT * FROM order_status_logs WHERE order_id=? ORDER BY id DESC LIMIT 50');$lg->execute([$id]);$logs=$lg->fetchAll();}catch(Throwable $e){}} }catch(Throwable $e){}
?>
<?php if($flash): ?><div class="ao-alert <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<?php if(!$o): ?><div class="ao-card"><h2>Sipariş bulunamadı</h2><a class="ao-btn" href="<?= url('admin/orders') ?>">Geri Dön</a></div><?php return; endif; ?>
<div class="ao-page-head"><div><h2><?= e($o['order_number']) ?> Sipariş Detayı</h2><p><?= e($o['first_name'].' '.$o['last_name'].' - '.$o['email']) ?></p></div><a class="ao-btn soft" href="<?= url('admin/orders') ?>">Siparişlere Dön</a></div>
<div class="ao-grid two"><div class="ao-card"><h3>Durum Yönetimi</h3><form method="post" action="<?= url('admin/orders/status') ?>" class="ao-form"><?= csrf_field() ?><input type="hidden" name="order_id" value="<?= (int)$o['id'] ?>"><label>Yeni Durum<select name="status"><option value="pending">Bekleyen</option><option value="active">Onayla / Provision</option><option value="fraud">Fraud İnceleme</option><option value="cancelled">İptal</option></select></label><label>Not<textarea name="note" rows="3"></textarea></label><button class="ao-btn">Durumu Güncelle</button></form></div><div class="ao-card"><h3>Özet</h3><p><b>Durum:</b> <?= e($o['status']) ?></p><p><b>Provision:</b> <?= e($o['provision_status']??'pending') ?></p><p><b>Fraud:</b> <?= (int)($o['fraud_score']??0) ?></p><p><b>Toplam:</b> <?= number_format((float)$o['total'],2,',','.') ?> ₺</p><?php if($invoice): ?><p><b>Fatura:</b> <?= e($invoice['invoice_number']) ?> / <?= e($invoice['status']) ?></p><a class="ao-mini-btn" href="<?= url('admin/accounting/invoice-pdf?id='.(int)$invoice['id']) ?>">PDF İndir</a><?php endif; ?></div></div>
<div class="ao-card"><h3>Ürünler</h3><table class="ao-table"><thead><tr><th>Ürün</th><th>Tip</th><th>Domain</th><th>Periyot</th><th>Tutar</th><th>Modül</th></tr></thead><tbody><?php foreach($items as $it): ?><tr><td><?= e($it['item_name']) ?></td><td><?= e($it['item_type']) ?></td><td><?= e($it['domain']) ?></td><td><?= e($it['billing_cycle']) ?></td><td><?= number_format((float)$it['price'],2,',','.') ?> ₺</td><td><?= e($it['module_name']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="ao-card"><h3>Durum Günlüğü</h3><table class="ao-table"><thead><tr><th>Tarih</th><th>İşlem</th><th>Eski</th><th>Yeni</th><th>Not</th></tr></thead><tbody><?php foreach($logs as $l): ?><tr><td><?= e($l['created_at']) ?></td><td><?= e($l['action']) ?></td><td><?= e($l['old_status']) ?></td><td><?= e($l['new_status']) ?></td><td><?= e($l['note']) ?></td></tr><?php endforeach; if(!$logs): ?><tr><td colspan="5">Henüz log yok.</td></tr><?php endif; ?></tbody></table></div>
